#87: fix the global time rounding
codingteam/Keter pull request #89
Opened 2020-02-02 18:05 UTC by ttldtor

I think three decimal places will be enough to know about the effect of portals on time

2020-02-02 18:09 UTC, ttldtor commented
Oh. Travis wants at least version 9

2020-02-03 15:32 UTC, ForNeVeR commented on src/main/scala/ru/org/codingteam/keter/scenes/game/GameViewModel.scala
> +  val statInfo: TextViewModel = new TextViewModel() {
Why do you need a type annotation here?

2020-02-03 15:32 UTC, ForNeVeR commented on src/main/scala/ru/org/codingteam/keter/scenes/game/GameViewModel.scala
> +          f"Time global/local: ${universe.globalEvents.timestamp}%.03f/${player.eventQueue.timestamp.toLong}"
Why are local and global time formatted differently?

2020-02-03 15:49 UTC, ForNeVeR requested changes

2020-02-03 15:49 UTC, ForNeVeR commented on src/main/scala/ru/org/codingteam/keter/scenes/game/GameViewModel.scala
> +          f"Time global/local: ${universe.globalEvents.timestamp}%.03f/${player.eventQueue.timestamp.toLong}"
We've decided that this needs to be consistent.

2020-02-03 16:02 UTC, ForNeVeR commented
Thanks for help!

2020-02-03 16:02 UTC, ForNeVeR approved these changes

2020-02-03 16:08 UTC, ttldtor commented
@ForNeVeR merge, please. I have no such rights: `You’re not authorized to merge this pull request. `

2020-02-03 16:13 UTC, merged